### ISSUE TITLE
bodo not support csv

### ISSUE THREAD

**Issue by PengWenChen** [Bodo-inc/Bodo-examples#58]
Hello, thanks for providing this great module.

I installed bodo by pip3 successfully.
However, when I run the `@bodo.jit`, it occur error that it has no attribute jit.
**"AttributeError: partially initialized module 'bodo' has no attribute 'jit' (most likely due to a circular import)**
How to fix this environment issue? Thank you
**The above issue is fixed.** 

I would like to ask whether bodo support csv files? Does it only support parquet? 
Thank you very much.

**Comment by hadia206** [comment]
Hi @PengWenChen 
Thanks for trying Bodo. 
To answer your question 

> I would like to ask whether bodo support csv files? Does it only support parquet?

Yes, Bodo supports CSV as well as other formats beside parquet. Please refer to our I/O documentation for list of supported data files and how to use them https://docs.bodo.ai/2022.4/file_io/

Also, here's an example that uses csv file [nyc-taxi](https://github.com/Bodo-inc/Bodo-examples/blob/3ea0c945ffa260218427a7f5c58fc99e14a7dfe6/notebooks/nyc-taxi.ipynb)

Waiting for more information about your environment to help you with error you see.

Thanks.
